### ISSUE TITLE
Epic: Integrating BadgerDB with libp2p for Controlled Write Access and Data Synchronization

### ISSUE THREAD

**Issue by teslashibe** [masa-finance/masa-oracle#146]
## Overview

This epic aims to add functionality to our network to record uptime data that is synchronized across nodes using BadgerDB. In our first release only one designated node will have write access to the database. We will use our underlying communication stack with GossipSub libp2p, for broadcasting node events and database updates.

### 1. Integrate BadgerDB
**Objective:** Integrate BadgerDB with the libp2p application, ensuring it's initialized at the start.

**Acceptance Criteria:**
- BadgerDB is initialized when a node starts.
- Nodes can perform read operations from BadgerDB.

```go
import (
    "log"

    badger "github.com/dgraph-io/badger/v3"
)

func initDB() *badger.DB {
    db, err := badger.Open(badger.DefaultOptions("/path/to/badgerdb"))
    if err != nil {
        log.Fatal(err)
    }
    return db
}
```

### 2. Designate a Writer Node
**Objective:** Designate a specific node with exclusive write access to the BadgerDB.

**Acceptance Criteria:**
- Only the designated writer node can perform write operations to the database.
- Other nodes are prevented from writing to the database.

```go
var allowedPeerID string = "12D3KooW..."

func canWrite(h host.Host) bool {
    return h.ID().String() == allowedPeerID
}
```

### 3. Implement GossipSub for Node Events
**Objective:** Use GossipSub to broadcast node join/leave events across the network.

**Acceptance Criteria:**
- Nodes broadcast a message when they join or leave.
- Other nodes receive these messages and can act accordingly.

#### Setup GossipSub

```go
import "github.com/libp2p/go-libp2p-pubsub"

ps, _ := pubsub.NewGossipSub(ctx, h)
```

#### Broadcast and Listen for Node Events

```go
// Broadcasting a join event
eventType := "join" // or "leave" for leave events
eventMessage := fmt.Sprintf("%s|%s|%d", eventType, h.ID(), time.Now().Unix())
ps.Publish("node-events", []byte(eventMessage))

// Listening for node events
sub, _ := ps.Subscribe("node-events")
go func() {
    for {
        msg, _ := sub.Next(ctx)
        log.Printf("Node event: %s\n", string(msg.Data))
    }
}()
```

### 4. Implement GossipSub for Database Synchronization
**Objective:** Use another GossipSub topic for synchronizing database updates across nodes.

**Acceptance Criteria:**
- The writer node publishes database updates.
- Other nodes subscribe to these updates and synchronize their local BadgerDB instances accordingly.

#### Broadcast and Listen for Database Updates

```go
// Broadcasting a database update
updateMessage := "db_update" // This should be more detailed, possibly including data identifiers or hashes
ps.Publish("db-sync", []byte(updateMessage))

// Listening for database updates
dbSub, _ := ps.Subscribe("db-sync")
go func() {
    for {
        msg, _ := dbSub.Next(ctx)
        log.Printf("Database update: %s\n", string(msg.Data))
        // Implement data fetching and local DB update logic
    }
}()
```

## Implementation Notes

- [ ] Implement security features, including authentication and encryption, to protect node communications and database transactions.
- [ ] Consider using more sophisticated conflict resolution strategies for database synchronization, especially if concurrent writes could occur.
- [ ] Test the system thoroughly under different network conditions and with varying numbers of nodes to ensure reliability and scalability.

## In progress
- [ ] Secure public key distribution https://github.com/masa-finance/masa-oracle/issues/149
- [ ] Single db writer who is the pubKey in the secure distribution https://github.com/masa-finance/masa-oracle/issues/148 

## Completed Tasks 

- [x] Add badgerdb and initialize badgerdb on startup https://github.com/masa-finance/masa-oracle/pull/147

**Comment by teslashibe** [comment]
BadgerDB docs: https://dgraph.io/docs/badger/

**Comment by jdutchak** [comment]
RE: 2. Designate a Writer Node thoughts

Do we want only 1 peer to be the authorized writer to the db? or do we want to setup a mapping for multiple nodes for scale?

```allowedPeerID := viper.GetString("ALLOWED_PEER_ID")```

vs something like ->

// pseudo
```
// AuthorizedNodes is a set of authorized nodes that can write to the database
type AuthorizedNodes map[peer.ID]bool


func CanWrite(h host.Host, data []byte, signature []byte) bool {
        if !isAuthorized(node.ID()) {
		return ErrNotAuthorized
	}
	...
}

// isAuthorized checks if a node is authorized to write to the database
func isAuthorized(nodeID peer.ID) bool {
	// Check if the node is in the list of authorized nodes
	for id := range authorizedNodes {
		if id == nodeID {
			return true
		}
	}
	return false
}

var authorizedNodes = AuthorizedNodes{
        authNodes := viper.GetStringMapStringSlice("ALLOWED_PEER_IDS")
	
	// "node1": true,
	// "node2": true,
}

**Comment by teslashibe** [comment]
Two concepts for sharing data:

1. Protocol - Quic for sharing public key when a node joins
2. Gossip - distribute the signed data to nodes so they can verify and write to their local DB

**Comment by jdutchak** [comment]
Can close this
