### ISSUE TITLE
Implement WorkHandler Interface for Modular Work Processing

### ISSUE THREAD

**Issue by restevens402** [masa-finance/masa-oracle#283]
## Description
To improve modularity and scalability in our work processing system, we need to implement a `WorkHandler` interface. Each type of work (e.g., LLMChat, Twitter, Web) will have its own handler implementing this interface, allowing for cleaner and more maintainable code.

## Tasks
- [ ] Define a `WorkHandler` interface with a `HandleWork` method.
- [ ] Implement the interface in separate structs for each work type (LLMChatHandler, TwitterHandler, etc.).
- [ ] Ensure each handler encapsulates the logic specific to processing its type of work.

## Acceptance Criteria
- Work processing logic for each type is encapsulated in its respective handler.
- The system can easily be extended to handle new types of work by implementing the `WorkHandler` interface.

As a general idea, I'm thinking something like this:

```
type WorkHandler interface {
    HandleWork(ctx actor.Context, workData map[string]string) error
}
```
Then implement
```
type LLMChatHandler struct{}

func (h *LLMChatHandler) HandleWork(ctx actor.Context, workData map[string]string) error {
    // Implementation for handling LLMChat work
}
```
