### ISSUE TITLE
Refactor Worker to Use WorkHandlers

### ISSUE THREAD

**Issue by restevens402** [masa-finance/masa-oracle#284]
## Description
Currently, our Worker actor's `Receive` method directly handles the logic for different types of work. This issue aims to refactor the Worker to use the `WorkHandler` interface, delegating work processing to the respective handlers based on the work type.

## Tasks
- [ ] Create a registry mapping work types to their corresponding `WorkHandler` instances.
- [ ] Modify the Worker's `Receive` method to look up and delegate work to the appropriate handler.
- [ ] Ensure that work delegation is done asynchronously to avoid blocking the actor's message loop.

## Acceptance Criteria
- The Worker actor uses `WorkHandler` instances to process different types of work.
- Work processing is performed asynchronously.
- The system's overall modularity and maintainability are improved.

We will need some kind of manager for getting the proper handler. It could be something as simple as a map and we could do something like:

```

var workHandlers = map[WorkerType]WorkHandler{
    WORKER.LLMChat:          &LLMChatHandler{},
    WORKER.Twitter:          &TwitterHandler{},
    // Add other handlers here
}


func (a *Worker) Receive(ctx actor.Context) {
    switch m := ctx.Message().(type) {
    case *messages.Work:
        workData := map[string]string{}
        err := json.Unmarshal([]byte(m.Data), &workData)
        if err != nil {
            logrus.Errorf("Error parsing work data: %v", err)
            return
        }

        handler, ok := workHandlers[WorkerType(workData["request"])]
        if !ok {
            logrus.Errorf("No handler found for work type: %s", workData["request"])
            return
        }

        go func() {
            if err := handler.HandleWork(ctx, workData); err != nil {
                logrus.Errorf("Error handling work: %v", err)
            }
        }()
    // Handle other message types
    }
}
```
