### ISSUE TITLE
Enhance SendWork Function for Asynchronous Execution

### ISSUE THREAD

**Issue by restevens402** [masa-finance/masa-oracle#285]
## Description
The `SendWork` function currently performs blocking operations when sending work to the self node and peers. This issue focuses on refactoring `SendWork` to dispatch work asynchronously, improving system efficiency and responsiveness.

## Tasks
- [ ] Abstract the logic for sending work to a node into a separate function.
- [ ] Use goroutines in `SendWork` to send work messages to both the self node and peers asynchronously.
- [ ] Include comprehensive error handling and logging within the asynchronous operations.

## Acceptance Criteria
- Work is dispatched to both the self node and peers without blocking the main thread.
- The system can handle multiple work dispatch operations concurrently.
- Errors during work dispatch are properly logged.

My initial thought was to add a goroutine for both local and peers in send work but send that to a separate function that encapsulates the commonality between the two types using a function:

```
func sendWorkToNode(node *masa.OracleNode, pid *actor.PID, message *messages.Work) {
    future := node.ActorEngine.RequestFuture(pid, message, 30*time.Second)
    result, err := future.Result()
    if err != nil {
        logrus.Errorf("Error receiving response: %v", err)
        return
    }
    response := result.(*messages.Response)
    msg, err := getResponseMessage(response)
    if err != nil {
        logrus.Errorf("Error getting response message: %v", err)
        return
    }
    workerDoneCh <- msg
}
```

Then make a small modification to SendWork

```
func SendWork(node *masa.OracleNode, m *pubsub2.Message) {
    props := actor.PropsFromProducer(NewWorker())
    selfPid := node.ActorEngine.Spawn(props)
    message := &messages.Work{Data: string(m.Data), Sender: selfPid, Id: m.ReceivedFrom.String()}

    // Send work to self node asynchronously
    go sendWorkToNode(node, selfPid, message)

    // Send work to peers asynchronously
    peers := node.Host.Network().Peers()
    for _, p := range peers {
        go func(peerID peer.ID) {
            conns := node.Host.Network().ConnsToPeer(peerID)
            for _, conn := range conns {
                addr := conn.RemoteMultiaddr()
                ipAddr, _ := addr.ValueForProtocol(multiaddr.P_IP4)
                if !isBootnode(ipAddr) {
                    spawned, err := node.ActorRemote.SpawnNamed(fmt.Sprintf("%s:4001", ipAddr), "worker", "peer", -1)
                    if err != nil {
                        logrus.Debugf("Spawned error %v", err)
                        return
                    }
                    spawnedPID := spawned.Pid
                    client := node.ActorEngine.Spawn(props)
                    node.ActorEngine.Send(spawnedPID, &messages.Connect{Sender: client})
                    sendWorkToNode(node, spawnedPID, message)
                }
            }
        }(p)
    }
}
```
