### ISSUE TITLE
Epic: Masa Protocol - Real Time Analytics Infrastructure

### ISSUE THREAD

**Issue by theMultitude** [masa-finance/masa-oracle#304]
Outlined here are the resources needed to implement #292 - Real-Time Decentralized Network Monitoring Stack with Consul, Prometheus, and Grafana.

On a high level there are five main tasks to be completed:

- [ ]  [Initialize Consul Cluster on AWS](https://github.com/masa-finance/masa-oracle/issues/300)
- [ ]  [Initialize Prometheus Server on AWS](https://github.com/masa-finance/masa-oracle/issues/301)
- [ ]  [Initialize Grafana Server on AWS](https://github.com/masa-finance/masa-oracle/issues/303)
- [ ]  [Add client docker specifications to Protocol Nodes](https://github.com/masa-finance/masa-oracle/issues/305)
- [ ]  #297 

How these function together:
1. The clients running Consul register with the Consul cluster on AWS.
2. The Prometheus server on AWS uses that registry to determine clients from whom it can gather information.
3. Prometheus on clients expose node based information that is periodically scraped by the Prometheus server.
4. Grafana pulls information from the Prometheus server and surfaces that information in visualizations.
