### ISSUE TITLE
Spike: Developer documentation improvements checklist

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-oracle#395]
**Problem statement:** 
Our existing protocol and bittensor documentation is outdated and lacks visual aids and comprehensive tutorials, making it challenging for users to onboard and understand the protocol + subnet efficiently.

**Acceptance Criteria:** 
- [ ] Complete ticket [#35](https://github.com/orgs/masa-finance/projects/14/views/1?pane=issue&itemId=74950111)
- [ ] Audit of existing content: Go through documentation and identify areas for improvement
- [ ] Content Update: Protocol documentation is fully updated to reflect current functionality.
- [ ] Create visual Aids: Diagrams, flowcharts, and screenshots are included where applicable.
- [ ] Create Tutorials:
- [ ] Step-by-step tutorials with visuals for key onboarding processes are added.
- [ ] User-Friendly Structure:
- [ ] Documentation is reorganized for easy navigation and includes a clear table of contents.
- [ ] Testing: Documentation is reviewed by test users, and feedback is incorporated.
- [ ] Accessibility: Content is accessible on all devices and is easy to read.
- [ ] Handoff to eng: Handoff to eng to implement updates 
- [ ] Publication:Documentation is published and communicated to users.
- [ ] Version Control: A version control system and change log are implemented.
- [ ] Maintenance Plan:A regular review and update plan is established.

**Audit/Resources:**
[Protocol ](https://docs.google.com/spreadsheets/d/1Z1_NrOOxVFIbKSY0HZEClNhxLDBgvsMVJUl0WglS0xg/edit?pli=1&gid=999148934#gid=999148934)
[Subnet ](https://docs.google.com/spreadsheets/d/1VUEe7Mw2aAtyWm-u2Uho-ChLUGJziu2D29cH75FMXnU/edit?gid=0#gid=0)
[FAQS ]( https://docs.google.com/document/d/1wTKpMCnVtQX1OVq5TXLOnq7cupnw6E9bj5ctxBgqjts/edit)

**Comment by lacyg4** [comment]
Audit documents for us to dig into @giovaroma 
[Protocol ](https://docs.google.com/spreadsheets/d/1Z1_NrOOxVFIbKSY0HZEClNhxLDBgvsMVJUl0WglS0xg/edit?pli=1&gid=999148934#gid=999148934)
[Subnet ](https://docs.google.com/spreadsheets/d/1VUEe7Mw2aAtyWm-u2Uho-ChLUGJziu2D29cH75FMXnU/edit?gid=0#gid=0)

**Comment by lacyg4** [comment]
@giovaroma added acceptance criteria

**Comment by giovaroma** [comment]
We will need to break down this ticket but great start in terms of acceptance criteria @lacyg4

**Comment by lacyg4** [comment]
@giovaroma added ticket #35 for quick start guide to acceptance criteria
