### ISSUE TITLE
feat: update event tracking to include the number of tweets returned by the worker who completes the work

### ISSUE THREAD

**Issue by teslashibe** [masa-finance/masa-oracle#548]
## Problem Statement
Currently, when a node completes work, we track the success status and peer ID using `TrackWorkCompletion`. However, we lack information about the quantity of objects (e.g., tweets, discord messages) processed during the work. This information is crucial for understanding the workload and efficiency of our system.

## Acceptance Criteria

- [ ] Modify the `TrackWorkCompletion` function to accept an additional parameter for the count of processed objects.
- [ ] Update the `Event` struct in `event.go` to include a field for storing the object count.
- [ ] Ensure that the object count is properly recorded and sent with the work completion event.
- [ ] The object count should be included in the logging output for work completion events.
- [ ] Update related functions like `TrackWorkDistribution` and `TrackWorkerFailure` to accommodate this new information if necessary.
- [ ] Update any relevant documentation or comments to reflect these changes.

**Comment by teslashibe** [comment]
This ticket depends on work in the API here: https://github.com/masa-finance/masa-protocol-api/issues/2

**Comment by teslashibe** [comment]
Add in these events for remote and local worker:

```
// TrackWorkDistribution records the distribution of work to a worker.
//
// Parameters:
// - remoteWorker: Boolean indicating if the work is sent to a remote worker (true) or executed locally (false)
// - peerId: String containing the peer ID
func (a *EventTracker) TrackWorkDistribution(remoteWorker bool, peerId string) {
	event := Event{
		Name:         WorkDistribution,
		PeerID:       peerId,
		WorkType:     WorkDistribution,
		RemoteWorker: remoteWorker,
	}
	err := a.TrackAndSendEvent(event, nil)
	if err != nil {
		logrus.Errorf("error tracking work distribution event: %s", err)
	}
}

// TrackWorkCompletion records the completion of a work item.
//
// Parameters:
// - success: Boolean indicating if the work was completed successfully
// - peerId: String containing the peer ID
func (a *EventTracker) TrackWorkCompletion(success bool, peerId string) {
	event := Event{
		Name:     WorkCompletion,
		PeerID:   peerId,
		WorkType: WorkCompletion,
		Success:  success,
	}
	err := a.TrackAndSendEvent(event, nil)
	if err != nil {
		logrus.Errorf("error tracking work completion event: %s", err)
	}
}

// TrackWorkerFailure records a failure that occurred during work execution.
//
// Parameters:
// - errorMessage: A string describing the error that occurred
// - peerId: String containing the peer ID
func (a *EventTracker) TrackWorkerFailure(errorMessage string, peerId string) {
	event := Event{
		Name:     WorkFailure,
		PeerID:   peerId,
		WorkType: WorkFailure,
		Error:    errorMessage,
	}
	err := a.TrackAndSendEvent(event, nil)
	if err != nil {
		logrus.Errorf("error tracking worker failure event: %s", err)
	}
}
```
